// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhEhx4LPmkdq4ev9Q05AeUl1cPyu8pdk',
    appId: '1:772850286062:web:3c208bb7f6d53dd1ebe2ff',
    messagingSenderId: '772850286062',
    projectId: 'iflow-fe711',
    authDomain: 'iflow-fe711.firebaseapp.com',
    storageBucket: 'iflow-fe711.appspot.com',
    measurementId: 'G-EBR3DTRYHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8hhg2-YUvszw12tQFUNKf5cCEc22bO4',
    appId: '1:772850286062:android:22567aff05a0f3d8ebe2ff',
    messagingSenderId: '772850286062',
    projectId: 'iflow-fe711',
    storageBucket: 'iflow-fe711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdi2Ho5fjU6uDxt66ervMLScCVwa6oEZ8',
    appId: '1:772850286062:ios:f1363acac9045f9eebe2ff',
    messagingSenderId: '772850286062',
    projectId: 'iflow-fe711',
    storageBucket: 'iflow-fe711.appspot.com',
    iosClientId: '772850286062-re1r9u49qs9fj0o7a3pigejqbq5djeus.apps.googleusercontent.com',
    iosBundleId: 'com.example.wifiAirflowControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdi2Ho5fjU6uDxt66ervMLScCVwa6oEZ8',
    appId: '1:772850286062:ios:f1363acac9045f9eebe2ff',
    messagingSenderId: '772850286062',
    projectId: 'iflow-fe711',
    storageBucket: 'iflow-fe711.appspot.com',
    iosClientId: '772850286062-re1r9u49qs9fj0o7a3pigejqbq5djeus.apps.googleusercontent.com',
    iosBundleId: 'com.example.wifiAirflowControl',
  );
}
